name: kick_chat
description: kick_chat allows you to read a Kick chat.
version: 1.7.1
homepage: https://github.com/LezdCS/kick_chat
repository: https://github.com/LezdCS/kick_chat

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.1
  dio: ^5.4.3+1
  ua_client_hints: ^1.4.0
  api_7tv: ^0.0.4
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
